version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    # env_file:
    #   - ./env/mongo.env
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      MONGO_USER: admin
      MONGO_PWD: password
    # env_file:
    #   - ./env/backend.env
    depends_on:
      - mongodb
    

  # frontend:

volumes:
  data: